services:
  - type: web
    name: ilana-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    # Force redeploy to use latest commit
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PINECONE_INDEX_NAME
        value: clinical-protocols
      - key: PINECONE_HOST
        value: https://clinical-protocols-gdwejfu.svc.eastus2-5e25.prod-azure.pinecone.io
      - key: AZURE_OPENAI_ENDPOINT
        value: https://protocol-talk.openai.azure.com/
      - key: AZURE_OPENAI_DEPLOYMENT
        value: gpt-4o-deployment
      - key: PUBMEDBERT_ENDPOINT_URL
        value: https://usz78oxlybv4xfh2.eastus.azure.endpoints.huggingface.cloud